// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_detail_date from "./routes/api/detail/date.ts";
import * as $api_detail_index from "./routes/api/detail/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_list_index from "./routes/api/list/index.ts";
import * as $api_monthly_id_ from "./routes/api/monthly/[id].ts";
import * as $api_monthly_index from "./routes/api/monthly/index.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $monthly_id_ from "./routes/monthly/[id].tsx";
import * as $monthly_create from "./routes/monthly/create.tsx";
import * as $monthly_detail_create_id_ from "./routes/monthly/detail/create/[id].tsx";
import * as $monthly_detail_edit_id_ from "./routes/monthly/detail/edit/[id].tsx";
import * as $monthly_detail_list_id_ from "./routes/monthly/detail/list/[id].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CreateMonthForm from "./islands/CreateMonthForm.tsx";
import * as $DetailMonthly from "./islands/DetailMonthly.tsx";
import * as $DetailReport from "./islands/DetailReport.tsx";
import * as $List from "./islands/List.tsx";
import * as $Month from "./islands/Month.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/detail/date.ts": $api_detail_date,
    "./routes/api/detail/index.ts": $api_detail_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/list/index.ts": $api_list_index,
    "./routes/api/monthly/[id].ts": $api_monthly_id_,
    "./routes/api/monthly/index.ts": $api_monthly_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/monthly/[id].tsx": $monthly_id_,
    "./routes/monthly/create.tsx": $monthly_create,
    "./routes/monthly/detail/create/[id].tsx": $monthly_detail_create_id_,
    "./routes/monthly/detail/edit/[id].tsx": $monthly_detail_edit_id_,
    "./routes/monthly/detail/list/[id].tsx": $monthly_detail_list_id_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/CreateMonthForm.tsx": $CreateMonthForm,
    "./islands/DetailMonthly.tsx": $DetailMonthly,
    "./islands/DetailReport.tsx": $DetailReport,
    "./islands/List.tsx": $List,
    "./islands/Month.tsx": $Month,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
