// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/list/[id].ts";
import * as $1 from "./routes/api/list/index.ts";
import * as $2 from "./routes/api/monthly/[id].ts";
import * as $3 from "./routes/api/monthly/index.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/monthly/[id].tsx";
import * as $6 from "./routes/monthly/create.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/CreateMonthForm.tsx";
import * as $$2 from "./islands/DetailMonthly.tsx";
import * as $$3 from "./islands/Month.tsx";

const manifest = {
  routes: {
    "./routes/api/list/[id].ts": $0,
    "./routes/api/list/index.ts": $1,
    "./routes/api/monthly/[id].ts": $2,
    "./routes/api/monthly/index.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/monthly/[id].tsx": $5,
    "./routes/monthly/create.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/CreateMonthForm.tsx": $$1,
    "./islands/DetailMonthly.tsx": $$2,
    "./islands/Month.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
